import type { RunType, TemperaturePreference } from "./types";

/**
 * Every tunable number in the recommendation engine lives here.
 *
 * The engine works on a single "comfort temperature" (°C): a blend of the
 * feels-like and actual temperature, shifted by intensity, preference, wind
 * and rain. Clothing thresholds below compare against that value.
 */
export const config = {
  /** Weight of apparent temperature vs. actual temperature in the baseline. */
  feelsLikeWeight: 0.7,

  /** Runs at least this long plan for the coolest part of the run. */
  longDurationMinutes: 75,
  /** For long runs, how far (0–1) to lean the baseline toward the minimum. */
  longDurationMinWeight: 0.5,

  /** Degrees added to the baseline for body heat generated by each run type. */
  intensityOffset: {
    easy: 0,
    long: -1, // easy effort plus gradual cooling over time
    tempo: 4,
    intervals: 5,
    race: 6,
  } satisfies Record<RunType, number>,

  /** Degrees added for personal temperature preference. */
  preferenceOffset: {
    cold: -4,
    normal: 0,
    hot: 4,
  } satisfies Record<TemperaturePreference, number>,

  wind: {
    /** km/h — strong enough to warrant a wind layer and a comfort penalty. */
    strong: 25,
    /** km/h gusts that count as strong wind on their own. */
    strongGust: 45,
    /** Extra comfort penalty (°C) for strong wind beyond feels-like. */
    strongPenalty: 1,
    /** Above this comfort temperature, wind alone won't add a layer. */
    layerBelowComfort: 15,
    /** Warning thresholds. */
    warnSpeed: 30,
    warnGust: 45,
    dangerSpeed: 50,
    dangerGust: 75,
  },

  rain: {
    /** Below this probability (%), rain is ignored. */
    lowProbability: 40,
    /** Long runs get more exposure, so react at a lower probability. */
    lowProbabilityLongRun: 30,
    /** Probability (%) treated as "rain is likely". */
    likelyProbability: 60,
    /** Expected mm over the run that counts as real rain. */
    heavyAmount: 1.5,
    /** Share of the run that is wet to count as prolonged rain. */
    prolongedFraction: 0.5,
    /** Probability per hour at which that hour counts as wet. */
    wetHourProbability: 50,
    /** Above this comfort temperature, skip rain jackets — they just trap heat. */
    jacketBelowComfort: 18,
    /** Comfort penalties (°C) for getting wet. */
    heavyPenalty: 2,
    showersPenalty: 1,
  },

  /** Comfort-temperature thresholds (°C) for each clothing choice. */
  clothing: {
    shortSleeveAbove: 10,
    thermalBelow: 1,
    shortsAbove: 8,
    halfTightsAbove: 6,
    thermalTightsBelow: -2,
    trousersBelow: -12,
    lightGlovesBelow: 6,
    warmGlovesBelow: -4,
    beanieBelow: 0,
    neckGaiterBelow: -4,
    /** Neck gaiter also when windy and below this. */
    neckGaiterWindyBelow: 0,
    windbreakerBelow: -1,
    insulatedJacketBelow: -10,
    mediumSocksBelow: 6,
    heavySocksBelow: -6,
    /** A cap keeps rain off your face when it's not cold enough for a beanie. */
    rainCapBelow: 12,
  },

  sun: {
    /** UV index at which sun protection is suggested. */
    uvForProtection: 3,
    /** Cloud cover (%) below which it's sunny enough for sunglasses. */
    sunnyCloudCover: 60,
  },

  /** Temperature bands (°C) used for explanations, on the baseline. */
  bands: {
    hot: 20,
    warm: 15,
    mild: 10,
    cool: 5,
    cold: 0,
  },

  warnings: {
    heatFeelsLike: 24,
    extremeHeatFeelsLike: 32,
    extremeColdFeelsLike: -15,
    /** °C change between start and end of the run worth calling out. */
    temperatureChange: 3,
    /** Feels-like at start below which the first minutes will feel cold. */
    coldStartFeelsLike: 8,
    highUv: 6,
    /** Air temperature (°C) at or below which precipitation may freeze. */
    iceTemperature: 1,
  },
} as const;

export type EngineConfig = typeof config;
